### ISSUE TITLE
API Gateway calls fail when LangChain>=0.1.0 is used

### ISSUE THREAD

**Issue by elmehdibelgasmi** [aws-samples/bedrock-multi-tenant-saas#2]
## Issue description:

When `invoke_model` Lambda Layer is configured with `langchain`>=0.1.0, API Gateway calls fail with the following error:

```
Traceback (most recent call last):
  File "/var/task/index.py", line 676, in lambda_handler
    return bedrock_handler(event)
  File "/var/task/index.py", line 500, in bedrock_handler
    response = bedrock_inference.invoke_text(body, model_kwargs)
  File "/var/task/index.py", line 221, in invoke_text
    raise e
  File "/var/task/index.py", line 176, in invoke_text
    request_body = LLMInputOutputAdapter.prepare_input(provider, body["inputs"], model_kwargs)
  File "/opt/python/langchain_community/llms/bedrock.py", line 118, in prepare_input
    input_body = {**model_kwargs}
TypeError: 'str' object is not a mapping
```

This is due to an attribute order change in the `prepare_input()` method of `LLMInputOutputAdapter` class:

[langchain<0.1.0:](https://api.python.langchain.com/en/v0.0.349/llms/langchain_community.llms.bedrock.LLMInputOutputAdapter.html#langchain_community.llms.bedrock.LLMInputOutputAdapter.prepare_input)
```
classmethod prepare_input(provider: str, prompt: str, model_kwargs: Dict[str, Any]) → Dict[str, Any]
```

[langchain>=0.1.0:](https://api.python.langchain.com/en/latest/llms/langchain_community.llms.bedrock.LLMInputOutputAdapter.html#langchain_community.llms.bedrock.LLMInputOutputAdapter.prepare_input)
```
classmethod prepare_input(provider: str, model_kwargs: Dict[str, Any], prompt: Optional[str] = None, system: Optional[str] = None, messages: Optional[List[Dict]] = None) → Dict[str, Any][[source]]
```

## Solution

Update `invoke_model` code as follows (line 176):
``` 
request_body = LLMInputOutputAdapter.prepare_input(provider, prompt=body["inputs"], model_kwargs=model_kwargs)
```

**Comment by elmehdibelgasmi** [comment]
Will submit a PR to fix the issue

**Comment by brunopistone** [comment]
Helllo @elmehdibelgasmi, thanks for opening this issue. 
Can you please share your python env, with module versions installed for Langchain, boto3, botocore, and the LLM you are currently testing?

We have updated the langchain library quite a long time ago, and most recently for supporting messages API from Claude 3, and we are not facing any issue

**Comment by elmehdibelgasmi** [comment]
Hello @brunopistone, 

In `main` branch, the following configuration present in the documentation (README.md) works for me:
```
[
  {
    "STACK_PREFIX": "", # unit 1 with dedicated SaaS resources
    "BEDROCK_ENDPOINT": "https://bedrock-runtime.{}.amazonaws.com", # bedrock-runtime endpoint used for invoking Amazon Bedrock
    "BEDROCK_REQUIREMENTS": "boto3>=1.28.57 awscli>=1.29.57 botocore>=1.31.57", # Requirements for Amazon Bedrock
    "LANGCHAIN_REQUIREMENTS": "aws-lambda-powertools langchain==0.0.349 pydantic PyYaml", # python modules installed for langchain layer
    "PANDAS_REQUIREMENTS": "pandas", # python modules installed for pandas layer
    "VPC_CIDR": "10.10.0.0/16" # CIDR used for the private VPC Env,
    "API_THROTTLING_RATE": 10000, #Throttling limit assigned to the usage plan
    "API_BURST_RATE": 5000 # Burst limit assigned to the usage plan
  }
]
```

The one in [setup/configs.json](https://github.com/aws-samples/bedrock-multi-tenant-saas/tree/main/setup/configs.json) does not work:

```
[
  {
    "STACK_PREFIX": "",
    "BEDROCK_ENDPOINT": "https://bedrock.{}.amazonaws.com",
    "BEDROCK_RUNTIME_ENDPOINT": "https://bedrock-runtime.{}.amazonaws.com",
    "BEDROCK_REQUIREMENTS": "boto3>=1.34.62 awscli>=1.32.62 botocore>=1.34.62",
    "LANGCHAIN_REQUIREMENTS": "aws-lambda-powertools langchain==0.1.12 pydantic PyYaml",
    "PANDAS_REQUIREMENTS": "pandas",
    "SAGEMAKER_ENDPOINTS": "",
    "VPC_CIDR": "10.10.0.0/16",
    "API_THROTTLING_RATE": 10000,
    "API_BURST_RATE": 5000
  }
]
```

I believe this is due to the change I described above.

**Comment by brunopistone** [comment]
Thanks for the heads up. Please use the example conf in the [config..json](https://github.com/aws-samples/bedrock-multi-tenant-saas/blob/main/setup/configs.json) file and let me know if you still face problems

**Comment by elmehdibelgasmi** [comment]
The [setup/configs.json](https://github.com/aws-samples/bedrock-multi-tenant-saas/tree/main/setup/configs.json) does not work. 
I have just submitted a fix if you have time to look at it. Thanks.

**Comment by brunopistone** [comment]
Tested and merged the PR. Thanks for the heads up!
